title: ZIO OpenFeature
description: A type-safe, ZIO-native implementation of the OpenFeature specification for Scala 3
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

url: https://etacassiopeia.github.io
baseurl: /zio-openfeature

aux_links:
  GitHub: https://github.com/EtaCassiopeia/zio-openfeature

nav_enabled: true
search_enabled: true

footer_content: "Copyright &copy; 2026 Mohsen Zainalpour. Distributed under the Apache 2.0 license."

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
